INSERT INTO SOCCER.EQUIPOS(ID,NOMBRE,DOMICILIO,TELEFONO,IDPRESIDENTE) VALUES(3,'CHIVAS','GUADALAJARA','34556984',1);
INSERT INTO SOCCER.EQUIPOS(ID,NOMBRE,DOMICILIO,TELEFONO,IDPRESIDENTE) VALUES(2,'AMERICA','DF','55692482',2);
INSERT INTO SOCCER.EQUIPOS(ID,NOMBRE,DOMICILIO,TELEFONO,IDPRESIDENTE) VALUES(1,'CRUZ AZUL','DF','55239581',3);
INSERT INTO SOCCER.EQUIPOS(ID,NOMBRE,DOMICILIO,TELEFONO,IDPRESIDENTE) VALUES(4,'ATLAS','GUADALAJARA','38254189',6);
INSERT INTO SOCCER.EQUIPOS(ID,NOMBRE,DOMICILIO,TELEFONO,IDPRESIDENTE) VALUES(5,'TECOS','ZAPOPAN','36287581',5);
INSERT INTO SOCCER.EQUIPOS(ID,NOMBRE,DOMICILIO,TELEFONO,IDPRESIDENTE) VALUES(6,'PUMAS','DF','55249581',4);