INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(52,1,1);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(59,1,1);


INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(2,2,1);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(1,2,2);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(3,3,1);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(9,3,3);


INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(28,4,1);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(7,5,1);


INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(15,6,2);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(5,6,2);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(7,7,2);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(58,7,3);


INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(7,7,2);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(58,7,3);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(16,8,3);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(1,8,3);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(45,9,1);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(56,10,1);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(46,10,1);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(6,11,1);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(5,11,2);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(49,12,1);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(58,13,1);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(54,15,1);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(5,15,2);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(5,16,1);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(34,16,3);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(2,17,3);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(1,17,4);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(9,18,2);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(8,18,2);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(40,19,1);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(12,19,3);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(3,20,2);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(12,20,2);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(31,21,3);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(22,22,1);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(13,22,3);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(11,23,1);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(6,24,1);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(8,24,1);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(34,25,2);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(8,25,2);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(59,26,1);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(15,27,1);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(22,28,2);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(39,28,1);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(29,29,5);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(13,29,5);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(36,30,2);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(3,30,3);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(34,31,3);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(11,31,3);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(17,32,1);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(1,33,1);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(40,34,1);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(9,35,1);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(3,36,1);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(7,37,1);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(53,38,1);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(18,38,1);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(15,39,1);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(8,39,1);


INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(57,40,1);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(4,40,2);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(3,41,4);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(5,41,1);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(7,42,1);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(12,42,3);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(4,43,3);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(5,43,3);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(6,44,2);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(51,45,3);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(4,46,2);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(18,46,2);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(47,47,1);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(7,47,1);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(33,48,3);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(44,48,4);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(4,49,2);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(9,51,1);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(36,51,2);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(14,52,2);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(22,52,1);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(21,53,3);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(5,53,1);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(13,54,1);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(54,54,4);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(57,55,1);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(46,55,2);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(57,55,1);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(40,55,2);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(54,56,1);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(5,56,1);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(54,56,1);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(5,56,1);


INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(14,57,2);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(7,57,2);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(59,58,1);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(40,58,1);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(25,59,1);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(48,59,2);

INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(45,60,1);
INSERT INTO PUNTUAJE_POR_JUGADOR(IDJUGADOR,IDJORNADA,GOLES) VALUES(32,60,1);