INSERT INTO SCHOOL.ANSWERS(id_questions,descriptions,is_correct) VALUES(1,'Answers 1','N');
INSERT INTO SCHOOL.ANSWERS(id_questions,descriptions,is_correct) VALUES(1,'Answers 2','Y');

INSERT INTO SCHOOL.ANSWERS(id_questions,descriptions,is_correct) VALUES(2,'Answers 3','N');
INSERT INTO SCHOOL.ANSWERS(id_questions,descriptions,is_correct) VALUES(2,'Answers 4','Y');

INSERT INTO SCHOOL.ANSWERS(id_questions,descriptions,is_correct) VALUES(3,'Answers 5','N');
INSERT INTO SCHOOL.ANSWERS(id_questions,descriptions,is_correct) VALUES(3,'Answers 6','Y');

INSERT INTO SCHOOL.ANSWERS(id_questions,descriptions,is_correct) VALUES(4,'Answers 7','N');
INSERT INTO SCHOOL.ANSWERS(id_questions,descriptions,is_correct) VALUES(4,'Answers 8','Y');

INSERT INTO SCHOOL.ANSWERS(id_questions,descriptions,is_correct) VALUES(5,'Answers 9','Y');
INSERT INTO SCHOOL.ANSWERS(id_questions,descriptions,is_correct) VALUES(5,'Answers 10','N');

INSERT INTO SCHOOL.ANSWERS(id_questions,descriptions,is_correct) VALUES(6,'Answers 11','N');
INSERT INTO SCHOOL.ANSWERS(id_questions,descriptions,is_correct) VALUES(6,'Answers 12','Y');

INSERT INTO SCHOOL.ANSWERS(id_questions,descriptions,is_correct) VALUES(7,'Answers 13','Y');
INSERT INTO SCHOOL.ANSWERS(id_questions,descriptions,is_correct) VALUES(7,'Answers 14?','N');

