
INSERT INTO SCHOOL.ASSIGMENT(id_activity,descriptions) VALUES(2,'Lorem ipsum dolor sit amet.1.');
INSERT INTO SCHOOL.ASSIGMENT(id_activity,descriptions) VALUES(3,'Lorem ipsum dolor sit amet.2.');
INSERT INTO SCHOOL.ASSIGMENT(id_activity,descriptions) VALUES(4,'Lorem ipsum dolor sit amet.3.');
INSERT INTO SCHOOL.ASSIGMENT(id_activity,descriptions) VALUES(5,'Lorem ipsum dolor sit amet.4.');

INSERT INTO SCHOOL.ASSIGMENT(id_activity,descriptions) VALUES(6,'Lorem ipsum dolor sit amet.5.');
INSERT INTO SCHOOL.ASSIGMENT(id_activity,descriptions) VALUES(7,'Lorem ipsum dolor sit amet.6.');
INSERT INTO SCHOOL.ASSIGMENT(id_activity,descriptions) VALUES(8,'Lorem ipsum dolor sit amet.7.');
INSERT INTO SCHOOL.ASSIGMENT(id_activity,descriptions) VALUES(9,'Lorem ipsum dolor sit amet.8.');