INSERT INTO SCHOOL.CLASSROOM(name_class) VALUES('Math 101');
INSERT INTO SCHOOL.CLASSROOM(name_class) VALUES('Computer Sciences');
INSERT INTO SCHOOL.CLASSROOM(name_class) VALUES('History Computer 101');
INSERT INTO SCHOOL.CLASSROOM(name_class) VALUES('Databases');

INSERT INTO SCHOOL.CLASSROOM(name_class) VALUES('Algorithm');
INSERT INTO SCHOOL.CLASSROOM(name_class) VALUES('Mobile Computing');
INSERT INTO SCHOOL.CLASSROOM(name_class) VALUES('Software Architecture');
INSERT INTO SCHOOL.CLASSROOM(name_class) VALUES('Software Process');
INSERT INTO SCHOOL.CLASSROOM(name_class) VALUES('Topics in Computing');
INSERT INTO SCHOOL.CLASSROOM(name_class) VALUES('Algorithms');