INSERT INTO SCHOOL.QUESTIONS(id_exams,descriptions,points) VALUES(1,'Question 1?',3);
INSERT INTO SCHOOL.QUESTIONS(id_exams,descriptions,points) VALUES(1,'Question 2?',2);
INSERT INTO SCHOOL.QUESTIONS(id_exams,descriptions,points) VALUES(1,'Question 3?',3);
INSERT INTO SCHOOL.QUESTIONS(id_exams,descriptions,points) VALUES(1,'Question 4?',2);
INSERT INTO SCHOOL.QUESTIONS(id_exams,descriptions,points) VALUES(2,'Question 5?',5);
INSERT INTO SCHOOL.QUESTIONS(id_exams,descriptions,points) VALUES(2,'Question 6?',3);
INSERT INTO SCHOOL.QUESTIONS(id_exams,descriptions,points) VALUES(2,'Question 7?',2);
