INSERT INTO SCHOOL.SECTIONS(id_class,name_sections,start_date,end_date) VALUES(1,'Introductions Math 101','1980-03-22','1980-03-23');
INSERT INTO SCHOOL.SECTIONS(id_class,name_sections,start_date,end_date) VALUES(1,'Additions','1980-03-22','1980-03-23');
INSERT INTO SCHOOL.SECTIONS(id_class,name_sections,start_date,end_date) VALUES(1,'Subtraction','1980-03-22','1980-03-23');
INSERT INTO SCHOOL.SECTIONS(id_class,name_sections,start_date,end_date) VALUES(1,'Introduction Algorithms','1980-03-22','1980-03-23');

INSERT INTO SCHOOL.SECTIONS(id_class,name_sections,start_date,end_date) VALUES(2,'Introductions Computer Sciences','1980-03-22','1980-03-23');

INSERT INTO SCHOOL.SECTIONS(id_class,name_sections,start_date,end_date) VALUES(2,'Analisis Computer Sciences','1980-03-22','1980-03-23');
INSERT INTO SCHOOL.SECTIONS(id_class,name_sections,start_date,end_date) VALUES(2,'Data mining','1980-03-22','1980-03-23');
INSERT INTO SCHOOL.SECTIONS(id_class,name_sections,start_date,end_date) VALUES(3,'History Introductions Software Architecture and Design','1980-03-22','1980-03-23');
INSERT INTO SCHOOL.SECTIONS(id_class,name_sections,start_date,end_date) VALUES(3,'Fundamentals Software Architecture and Design','1980-03-22','1980-03-23');
INSERT INTO SCHOOL.SECTIONS(id_class,name_sections,start_date,end_date) VALUES(3,'Microservices','1980-03-22','1980-03-23');