INSERT INTO SCHOOL.USER(first_name,last_name,email) VALUES('Jose Antonio','Gonzalez Castro','jose@gmail.com');
INSERT INTO SCHOOL.USER(first_name,last_name,email) VALUES('Antonio de Jesus','Gonzalez Castro','jesus@gmail.com');
INSERT INTO SCHOOL.USER(first_name,last_name,email) VALUES('Maria Jose','Gonzalez Castro','maria@gmail.com');
INSERT INTO SCHOOL.USER(first_name,last_name,email) VALUES('Mariela','Gonzalez Sanchez','marielae@gmail.com');
INSERT INTO SCHOOL.USER(first_name,last_name,email) VALUES('John','Smith','john@gmail.com');
INSERT INTO SCHOOL.USER(first_name,last_name,email) VALUES('Rodrigo','Doe','rodrigo@gmail.com');


INSERT INTO SCHOOL.USER(first_name,last_name,email) VALUES('Josh','Martinez Sanchez','josh@gmail.com');
INSERT INTO SCHOOL.USER(first_name,last_name,email) VALUES('Zacbe','Gonzalez Almenara','zacbe@gmail.com');
INSERT INTO SCHOOL.USER(first_name,last_name,email) VALUES('Miguel','Trujano','miguel@gmail.com');
INSERT INTO SCHOOL.USER(first_name,last_name,email) VALUES('Cesar','Yañez','cesar@gmail.com');


INSERT INTO SCHOOL.USER(first_name,last_name,email) VALUES('Sofia Amanda','Gonzalez','sofia@gmail.com');
INSERT INTO SCHOOL.USER(first_name,last_name,email) VALUES('Henrry','Jimenez','henrry@gmail.com');
INSERT INTO SCHOOL.USER(first_name,last_name,email) VALUES('Herman','Lopez','herman@gmail.com');
INSERT INTO SCHOOL.USER(first_name,last_name,email) VALUES('Gabriel','Cueto','grabriel@gmail.com');
INSERT INTO SCHOOL.USER(first_name,last_name,email) VALUES('Adrian','Blasio Encesio','adrian@gmail.com');
INSERT INTO SCHOOL.USER(first_name,last_name,email) VALUES('Liam Aristides','Gonzalez Gonzalez','liam@gmail.com');


INSERT INTO SCHOOL.USER(first_name,last_name,email) VALUES('Andrea','Martinez Castro','andrea@gmail.com');
INSERT INTO SCHOOL.USER(first_name,last_name,email) VALUES('Jose','Solis','josesolis@gmail.com');
INSERT INTO SCHOOL.USER(first_name,last_name,email) VALUES('Alfredo','Contreras','alfredo@gmail.com');
INSERT INTO SCHOOL.USER(first_name,last_name,email) VALUES('Daniel','Covarrubias','daniel@gmail.com');