INSERT INTO SOCCER.CANCHA(ID,NOMBRE,DOMICILIOS,IDESTADOS) VALUES(4,'ESTADIO JALISCO', 'CALZADA INDEPENDENCIA 3842 GUADALAJARA JALISCO',1);
INSERT INTO SOCCER.CANCHA(ID,NOMBRE,DOMICILIOS,IDESTADOS) VALUES(5,'ESTADIO 3 DE MARZO', 'AV. PATRIA 59820 ZAPOPAN JALISCO',1);
INSERT INTO SOCCER.CANCHA(ID,NOMBRE,DOMICILIOS,IDESTADOS) VALUES(2,'ESTADIO AZTECA', 'AV. DEL IMAN 47298 SANTA URSULA MEXICO DF',1);
INSERT INTO SOCCER.CANCHA(ID,NOMBRE,DOMICILIOS,IDESTADOS) VALUES(6,'ESTADIO UNIVERSITARIO', 'AV. INSURGENTES SUR 29820 MEXICO, DF',1);
INSERT INTO SOCCER.CANCHA(ID,NOMBRE,DOMICILIOS,IDESTADOS) VALUES(3,'ESTADIO NUEVO CHIVAS', 'AV. VALLARTA 39820 ZAPOPAN JALISCO',1);
INSERT INTO SOCCER.CANCHA(ID,NOMBRE,DOMICILIOS,IDESTADOS) VALUES(1,'ESTADIO AZUL', 'CAROLINA 4738 CIUDAD DE LOS DEPORTES MEXICO',1);