
CREATE SCHEMA SOCCER;
	
SET SCHEMA = SOCCER;

--TABLAS

CREATE TABLE SOCCER.PERSONA (
	ID INT NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1 ), 
	PRIMARY KEY (ID), 
	NOMBRE VARCHAR(30), 
	APELLIDO VARCHAR(30), 
	TELEFONO NVARCHAR(30) DEFAULT NULL);
	
	
CREATE TABLE SOCCER.ESTADOS (
	ID INT NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1 ), 
	PRIMARY KEY (ID), 
	ESTADO VARCHAR(30));

CREATE TABLE SOCCER.PRESIDENTE (
	ID INT NOT NULL, 
	PRIMARY KEY (ID), 
	IDPERSONA INT,
	PERIODO VARCHAR(30),
	FOREIGN KEY (IDPERSONA)
     REFERENCES SOCCER.PERSONA(ID) ON DELETE CASCADE
 );





CREATE TABLE SOCCER.EQUIPOS (
	ID INT NOT NULL, 
	PRIMARY KEY (ID),
	NOMBRE VARCHAR(30),
	DOMICILIO VARCHAR(30), 
	TELEFONO VARCHAR(30), 
	IDPRESIDENTE INT,
	FOREIGN KEY (IDPRESIDENTE)
     REFERENCES SOCCER.PRESIDENTE(ID) ON DELETE CASCADE
	);
 	
	
CREATE TABLE SOCCER.JUGADOR (
	ID INT NOT NULL, 
	PRIMARY KEY (ID), 
	IDPERSONA INT, 
	IDEQUIPO INT, 
	FECHANACIMIENTO DATE,
	FOREIGN KEY (IDEQUIPO)
     REFERENCES SOCCER.EQUIPOS (ID)  ON DELETE CASCADE,
	FOREIGN KEY (IDPERSONA)
     REFERENCES SOCCER.PERSONA (ID)  ON DELETE CASCADE);
    
     CREATE TABLE SOCCER.ARBITRO (
	CLAVE_ARBITRO INT NOT NULL, 
	PRIMARY KEY (CLAVE_ARBITRO), 
	IDPERSONA INT,
	DOMICILIO VARCHAR(50), 
	SKILL INT,
	FOREIGN KEY (IDPERSONA)
     REFERENCES SOCCER.PERSONA(ID) ON DELETE CASCADE
 );

CREATE TABLE SOCCER.CANCHA (
	ID INT NOT NULL, 
	PRIMARY KEY (ID),
	NOMBRE VARCHAR(50),
	DOMICILIOS VARCHAR(50),  
	IDESTADOS INT,
	FOREIGN KEY (IDESTADOS)
     REFERENCES SOCCER.ESTADOS (ID) ON DELETE CASCADE);

	
CREATE TABLE SOCCER.JORNADA (
	ID INT NOT NULL, 
	PRIMARY KEY (ID), 
	IDLOCAL INT,
	IDVISITAS INT,  
	IDCANCHA INT, 
	FECHA DATE, 
	HORA TIME,
	GOLESLOCAL INT,  
	GOLESVISITAS INT,
	 FOREIGN KEY (IDCANCHA)
     REFERENCES SOCCER.CANCHA (ID) ON DELETE CASCADE,
	FOREIGN KEY (IDVISITAS)
     REFERENCES SOCCER.EQUIPOS (ID) ON DELETE CASCADE,
	FOREIGN KEY (IDLOCAL)
     REFERENCES SOCCER.EQUIPOS (ID) ON DELETE CASCADE );
   
	
	
	
	CREATE TABLE SOCCER.DIRIGUE_POR (
	IDJORNADA INT NOT NULL, 
	IDARBITRO INT NOT NULL,
	PARTIDO INT NOT NULL,
	FOREIGN KEY (IDJORNADA)
     REFERENCES SOCCER.JORNADA (ID) ON DELETE CASCADE,
	FOREIGN KEY (IDARBITRO)
     REFERENCES SOCCER.ARBITRO (CLAVE_ARBITRO) ON DELETE CASCADE
);

CREATE TABLE SOCCER.JORNADA (
	ID INT NOT NULL, 
	IDLOCAL INT,
	IDVISITAS INT,  
	IDCANCHA INT, 
	FECHA DATE, 
	HORA TIME,
	GOLESLOCAL INT,  
	GOLESVISITAS INT,
	 FOREIGN KEY (IDCANCHA)
     REFERENCES SOCCER.CANCHA (ID) ON DELETE CASCADE,
	FOREIGN KEY (IDVISITAS)
     REFERENCES SOCCER.EQUIPOS (ID) ON DELETE CASCADE,
	FOREIGN KEY (IDLOCAL)
     REFERENCES SOCCER.EQUIPOS (ID) ON DELETE CASCADE );



	 CREATE TABLE PUNTUAJE_POR_JUGADOR (
	ID SERIAL PRIMARY KEY
	IDJUGADOR INT NOT NULL, 
	IDJORNADA INT NOT NULL,
	GOLES INT NOT NULL,
	FOREIGN KEY (IDJORNADA)
     REFERENCES JORNADA (ID) ON DELETE CASCADE
	FOREIGN KEY (IDJUGADOR)
     REFERENCES JUGADOR (ID) ON DELETE CASCADE);