INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('JUAN','PEREZ'); --1
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('FULANO','DETAL');--2
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('CONEJO', 'RODRIGUEZ');--3
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('LUIS', 'HERNANDEZ');--4
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('GENARO', 'PELAES');--5
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('LENARDO', 'GONZALEZ');--6
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('ANTONIO', 'SOLIS');--7
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('JOSE', 'RODRIGUEZ');--8
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('ARMANDO', 'RAMIREZ');--9
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('RAUL', 'ORTIZ');--10
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('GABRIEL', 'HERRERA');--11
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('ANDRES', 'GUARDADO');--12
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('ROBERTO', 'LUEVANOS');--13
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('DARIO', 'FRANCO');--14
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('STEVEN', 'SANDOVAL');--15
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('FEDERICO', 'ALVAREZ');--16
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('MANUEL', 'VERDIA');--17
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('ALEJANDRO', 'TORRES');--18
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('FERNANDO', 'DE LA MORA');--19
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('CARLOS', 'HURTADO');--20
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('JUAN', 'ROMERO');--21
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('JOSE', 'CAZAREZ');--22
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('EDUARDO', 'ESPINOZA');--23
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('MARCO', 'SOLIS');--24
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('RICARDO', 'MONTANER');--25
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('MIGUEL', 'GOMEZ');--26
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('AARON', 'CASTRO');--27
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('PEDRO', 'FERNANDEZ');--28
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('LUIS', 'GARCIA');--29
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('SERGIO', 'BOLA—OS');--30
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('DANIEL', 'GUZMAN');--31
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('RENE', 'REYNA');--32
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('FELIX', 'GRECO');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('HECTOR', 'JIMENEZ');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('ISRAEL', 'PE—A');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('RAMIRO', 'MEZA');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('JUAN', 'CANTORAL');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('FULANO', 'DETAL');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('LUIS', 'MARTINEZ');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('GENARO', 'CARDENAS');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('CONEJO', 'OBRADOR');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('LEONARDO', 'LOPEZ');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('ANTONIO', 'MENDEZ');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('JOSE', 'SOLIS');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('RAUL', 'HUERTA');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('ARMANDO', 'MORALES');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('GABRIEL', 'CERVANTES');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('ANDRES', 'GONZALEZ');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('ROBERTO', 'GARCIA');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('DARIO', 'PEREZ');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('FEDERICO', 'BRIONES');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('MANUEL', 'PEREZ');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('CONEJO', 'PEREZ');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('ALEJANDRO', 'FERNANDEZ');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('RICARDO', 'PELAES');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('MIGUEL', 'HERRERA');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('SERGIO', 'FERNANDEZ');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('ANTONIO', 'AGUILAR');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO) VALUES('CONEJO', 'PEREZ');

INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('JORGE','VERGARA','36289543');--60
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('GUILLERMO','CA—EDO','55938275');--61
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('CARLOS','HERMOSILLO','55213409');--62
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('ALVARO','CARRILLO','38526941');--63
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('JESUS','LEA—O','38741259');--64
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('JORGE','ORTIZ','55178920');--65


INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('ORLANDO','HERNANDEZ','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('FERNANDO','LINARES','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('JORGE','PEREZ','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('ANTONIO','SOLIS','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('JOSE','TORRES','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('RAMIRO','RAMIREZ','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('RODRIGO','AVALOS','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('JOSUE','GALEANA','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('DANIEL','VARGAS','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('ALFREDO','JIMENEZ','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('ANDRES','GARCIA','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('GUADALUPE','JIMENEZ','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('PEPE','MARTINEZ','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('GUILLERMO','SANCHEZ','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('RICARDO','TAVARES','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('LUIS','GARCIA','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('GERARDO','QUINTERO','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('ALONSO','FERNANDEZ','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('SANTIAGO','PEREZ','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('ALEJANDRO','FERNANDEZ','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('FERNANDO','GARCIA','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('FERMIN','RIESTRA','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('LEONARDO','GARCIA','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('JUAN','PEREZ','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('JOSE','TORRES','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('MIGUEL','HERNANDEZ','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('RAMIRO','RODRIGUEZ','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('RAUL','HUERTA','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('PEDRO','FERNANDDEZ','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('VICENTE','FERNANDEZ','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('JOSUE','ANAYA','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('GUILLERMO','ZAPATA','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('CARLOS','VILLA','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('JULIO','LOPEZ','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('EDGAR','GARCIA','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('ABRAHAM','JIMENEZ','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('MARCO','SOLIS','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('DAVID','GALEANA','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('JESUS','GARCIA','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('FELIPE','TOVAR','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('APOLO','ALVAREZ','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('EFREN','RAMIREZ','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('EFRAIN','GARCIA','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('DANIEL','GARCIA','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('FERNANDO','GARCIA','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('ANDRES','GARCIA','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('JOSE','RODRIGUEZ','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('STEVEN','SANDOVAL','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('ALONSO','HERRERA','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('ANTONIO','MAGALLANES','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('FEDERICO','AGUINAGA','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('RUBEN','LEDESMA','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('LUIS','PEREZ','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('JOSE','ROMO','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('RAUL','BARAJAS','34569650');
INSERT INTO SOCCER.PERSONA (NOMBRE, APELLIDO,TELEFONO) VALUES('TEODORO','GARCIA','34569650');