INSERT INTO ACTIVITY(id_class,name_activity,start_date,end_date) VALUES(1,"Deliver sums","1980-03-22","1980-03-23");
INSERT INTO ACTIVITY(id_class,name_activity,start_date,end_date) VALUES(1,"Solve Exercises","1980-03-22","1980-03-23");
INSERT INTO ACTIVITY(id_class,name_activity,start_date,end_date) VALUES(1,"Solve Exercises Subtraction","1980-03-22","1980-03-23");
INSERT INTO ACTIVITY(id_class,name_activity,start_date,end_date) VALUES(2,"Make a resumme introductions Computer Sciences","1980-03-22","1980-03-23");

INSERT INTO ACTIVITY(id_class,name_activity,start_date,end_date) VALUES(2,"Implement a analisis Computer Sciences","1980-03-22","1980-03-23");
INSERT INTO ACTIVITY(id_class,name_activity,start_date,end_date) VALUES(2,"Do a test data mining","1980-03-22","1980-03-23");
INSERT INTO ACTIVITY(id_class,name_activity,start_date,end_date) VALUES(3,"Make a resumme  History Introductions Software Architecture and Design","1980-03-22","1980-03-23");
INSERT INTO ACTIVITY(id_class,name_activity,start_date,end_date) VALUES(3,"Do a test Fundamentals Software Architecture and Design","1980-03-22","1980-03-23");
INSERT INTO ACTIVITY(id_class,name_activity,start_date,end_date) VALUES(3,"Create a Microservices","1980-03-22","1980-03-23");
INSERT INTO ACTIVITY(id_class,name_activity,start_date,end_date) VALUES(1,"Make a resumme Introduction Algorithms","1980-03-22","1980-03-23");