INSERT INTO ANSWERS(id_questions,descriptions,is_correct) VALUES(1,"Answers 1");
INSERT INTO ANSWERS(id_questions,descriptions,is_correct) VALUES(1,"Answers 2",true);

INSERT INTO ANSWERS(id_questions,descriptions,is_correct) VALUES(2,"Answers 3");
INSERT INTO ANSWERS(id_questions,descriptions,is_correct) VALUES(2,"Answers 4",true);

INSERT INTO ANSWERS(id_questions,descriptions,is_correct) VALUES(3,"Answers 5");
INSERT INTO ANSWERS(id_questions,descriptions,is_correct) VALUES(3,"Answers 6",true);

INSERT INTO ANSWERS(id_questions,descriptions,is_correct) VALUES(4,"Answers 7");
INSERT INTO ANSWERS(id_questions,descriptions,is_correct) VALUES(4,"Answers 8",true);

INSERT INTO ANSWERS(id_questions,descriptions,is_correct) VALUES(5,"Answers 9",true);
INSERT INTO ANSWERS(id_questions,descriptions,is_correct) VALUES(5,"Answers 10");

INSERT INTO ANSWERS(id_questions,descriptions,is_correct) VALUES(6,"Answers 11");
INSERT INTO ANSWERS(id_questions,descriptions,is_correct) VALUES(6,"Answers 12",true);

INSERT INTO ANSWERS(id_questions,descriptions,is_correct) VALUES(7,"Answers 13",true);
INSERT INTO ANSWERS(id_questions,descriptions,is_correct) VALUES(7,"Answers 14?");

INSERT INTO ANSWERS(id_questions,descriptions,is_correct) VALUES(8,"Answers 15");
INSERT INTO ANSWERS(id_questions,descriptions,is_correct) VALUES(8,"Answers 16",true);

INSERT INTO ANSWERS(id_questions,descriptions,is_correct) VALUES(9,"Answers 17",true);
INSERT INTO ANSWERS(id_questions,descriptions,is_correct) VALUES(9,"Answers 18");

INSERT INTO ANSWERS(id_questions,descriptions,is_correct) VALUES(10,"Answers 19");
INSERT INTO ANSWERS(id_questions,descriptions,is_correct) VALUES(10,"Answers 20",true);
