INSERT INTO CLASSROOM(name_class) VALUES("Math 101");
INSERT INTO CLASSROOM(name_class) VALUES("Computer Sciences");
INSERT INTO CLASSROOM(name_class) VALUES("History Computer 101");
INSERT INTO CLASSROOM(name_class) VALUES("Databases");

INSERT INTO CLASSROOM(name_class) VALUES("Algorithm");
INSERT INTO CLASSROOM(name_class) VALUES("Mobile Computing");
INSERT INTO CLASSROOM(name_class) VALUES("Software Architecture and Design");
INSERT INTO CLASSROOM(name_class) VALUES("Software Process Management");
INSERT INTO CLASSROOM(name_class) VALUES("Advanced Topics in Computing");
INSERT INTO CLASSROOM(name_class) VALUES("Introduction Algorithms");